name: Build Lean Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Lean toolchain
        uses: leanprover/lean-action@v1
        with:
          toolchain: leanprover/lean4:stable

      - name: Run lake update
        run: lake update

      - name: Build project
        run: lake build
