name: Build Lean Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Lean
        uses: leanprover/lean-action@v1
        with:
          toolchain: leanprover/lean4:v4.21.0

      - name: Build project with lake
        run: |
          lake update
          lake build
